<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [4]:
def greeting(name):
    if name == 'Batman':
        return'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
greeting("Super Man")

'Hello Super Man!'

In [5]:
greet=greeting(name='Super Man')
print(greet)

Hello Super Man!


In [6]:
print(greeting(name='Super Man'))

Hello Super Man!


In [12]:
def basic_stats(numbers):
    np_numbers = np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

In [29]:
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])
print(list_mean)

3.0


### 1.2 Named functions that don’t return

### 1.3 Anonymous functions

In [22]:
my_short_function = lambda name: f"Hello {name}!"

In [23]:
my_short_function(name="Super Man")

'Hello Super Man!'

In [30]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [31]:
sorted(numbers, key=lambda x: x[1])

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [32]:
sorted(numbers, key=lambda x:sum(x))

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [33]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [34]:
greeting()

'Hello no one!'

In [35]:
print('I', 'am', 'Batman!')            

I am Batman!


In [36]:
print('I','am','Batman!', sep='---')

I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

In [37]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'
greeting ('Me')

'Hello Me!'

Because the return function with its appropriate indentation allocated help to make this code works as how an else can does.Return give the output by jumping out of the function with the return value. 

## Exercise 2 :  Calculator functions

In [2]:
x=np.array([36, 34, 44, 76, 27, 15])
y=np.array([64, 66, 56, 24, 73, 0])

def add(x,y):
    return x+y
print(add(x,y))

[100 100 100 100 100  15]


In [61]:
def substract(x,y):
    return x-y
print(substract(x,y))

[-28 -32 -12  52 -46  15]


In [71]:
def multiply(x,y):
    return x*y
print(multiply(x,y))

[2304 2244 2464 1824 1971    0]


In [3]:
def divide(x,y):
    y = np.array(y)
    if 0 in y:
        return 
    else:
        return x/y
print(divide(x,y))

None


## Exercise 3 :  max_info() with NumPy

In [13]:
number = np.array([40, 27, 83, 44, 74, 51, 76, 77, 10, 49])

def max_info(numbers):
    return np.max(numbers), np.argmax(numbers)
    
max_info(number)



(83, 2)