<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [1]:
x = 10
assert x >=0, "x is becoming negative!"


In [2]:
x = -1
assert x >=0, "x is becoming negative!"

AssertionError: x is becoming negative!

### 1.2 try-except

In [3]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.2
The square of 2 is 4!


In [4]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.hahaha
Oh oh! I cannot square hahaha!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [5]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c
print(funny_add(1,2))

121


In [6]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c
print(funny_add(1,2,3))

321


In [7]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c
print(funny_add(a=1, b=2))

121


In [8]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c
print(funny_add(c=3, b=1, a=2))

312


In [9]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c
print(funny_add(1, c=3, b=2))

321


In [10]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c
print(funny_add(1, b=2))

121


In [11]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c
print(funny_add(a=2, 1))

SyntaxError: positional argument follows keyword argument (3466288683.py, line 3)

### 2.2 Docstrings

### 2.2 Docstrings

In [12]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [13]:
def my_function(angle, trig_function):
        return trig_function(angle)

my_function(np.pi/2, np.sin)        


1.0

In [14]:
def my_function(angle, trig_function):
        return trig_function(angle)

my_function(np.pi/2, np.cos)        


6.123233995736766e-17

In [15]:
def my_function(angle, trig_function):
        return trig_function(angle)

my_function(np.pi/2, lambda x: np.cos(2*x))        


-1.0

### 2.4 More unpacking

In [16]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [17]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [18]:
x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

1 [2, 3, 4] 5


In [19]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


## Exercise 1 :  A better calculator I

In [24]:
import numpy as np
x=np.array([36, 34, 44, 76, 27, 15])
y=np.array([64, 66, 56, 24, 73, 0])

In [32]:
def add(x,y):
    return x+y
print(add(x,y))

[100 100 100 100 100  15]


In [33]:
def substract(x,y):
    return x-y
print(substract(x,y))

[-28 -32 -12  52 -46  15]


In [34]:
def multiply(x,y):
    return x*y
print(multiply(x,y))

[2304 2244 2464 1824 1971    0]


In [44]:
def divide(x,y):
    assert np.all(y != 0), "None"
    return x/y
print(divide(x,y))

AssertionError: None

## Exercise 2 :  A better calculator II

In [65]:
import numpy as np
x=np.array([36, 34, 44, 76, 27, 15])
y=np.array([64, 66, 56, 24, 73, 0])

def divide(x,y):
    try:
        assert y != 0, "None"
        return x/y
    except:
        return(f"Oh oh! Cannot divide if {y}!")
print(divide(x,y))

Oh oh! Cannot divide if [64 66 56 24 73  0]!
