<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [5]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
np_array = np.array(py_list)

x = py_list
x[0]


'a1'

In [9]:
x[-1]
x[0:3]
x[1:6]
x[1:6:2]
x[5:]
x[:5]
x[5:2:-1]
x[::-1]

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

In [26]:
x[::-1]

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

In [18]:
x[-1]

'j10'

### 1.2 Subsetting by masking (Arrays only)

In [12]:
np_array = np.array([1,2,3,4,5,6,7,8,9,10])
my_mask = np_array >3
print(my_mask)


[False False False  True  True  True  True  True  True  True]


In [13]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [14]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [15]:
np_array[~(np_array > 3)]

array([1, 2, 3])

In [16]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [17]:
np_array[(np_array < 3)|(np_array > 8)]

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [18]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [19]:
py_list_2d[3]

[4, 'D']

In [20]:
py_list_2d[3][0]

4

In [21]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [22]:
py_list_2d[:3][0]

[1, 'A']

In [23]:
py_list_2d[3:6][0]

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [27]:
np_array_2d = np.array ([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]])

In [27]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

In [28]:
np_array_2d[3,0]

'4'

In [28]:
np_array_2d[3][0]

'4'

In [29]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [30]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [31]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [32]:
np_array_2d[:,0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [33]:
x=[1]*10
x

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [34]:
x=[1]
x= x+ [2]
x= x+ [3]
x= x+ [4]
x

[1, 2, 3, 4]

In [35]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [36]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [37]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [38]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [43]:
a=(1,2,3)
print (a[0])

1


In [59]:
a += -1,
print(a[10])

-1


### 2.2 Be VERY careful when copying

In [43]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

Term| Brief description
:-|:--:
Subsetting|Selecting 
Indexing|Selecting an element
Slicing|Selecting a range of element
Masking|Allow only certain subset and *mask other elements*

## Exercise 2 :  Show me the ‘odd’ letters

In [61]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


In [68]:
x= np_array_2d[:,0].astype(int)
x %=2
mask = x ==1
print(mask)

[ True  True False False  True  True False False False  True]


In [70]:
np_array_2d[mask,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')