<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [10]:
import numpy as np
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
np_super_names = np.array(py_super_names)
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [24]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [5]:
print(py_real_names[0])`


Natasha Romanoff


In [11]:
print(py_super_names[0])

Black Widow


In [7]:
print(py_super_names[2])

Doctor Strange


In [8]:
print(py_super_names[-1])

Doctor Strange


### 1.3 Accessing data from a dictionary

In [25]:
print(superhero_info["Natasha Romanoff"])

Black Widow


In [11]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [12]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

In [26]:
print(list(superhero_info.values()).index("Iron Man"))
print(list(superhero_info.keys()))

1
['Natasha Romanoff', 'Tony Stark', 'Stephen Strange']


### 1.4 Higher dimensional lists

In [13]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

## 2 Lists vs. Arrays

### 2.1 Size

In [27]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
np_array_2d = np.array(py_list_2d)

In [15]:
len(py_list_2d)

10

In [17]:
len(np_array_2d)

10

In [18]:
np_array_2d.shape

(10, 2)

In [28]:
print(np_array_2d)

[['1' 'A']
 ['2' 'B']
 ['3' 'C']
 ['4' 'D']
 ['5' 'E']
 ['6' 'F']
 ['7' 'G']
 ['8' 'H']
 ['9' 'I']
 ['10' 'J']]


### 2.2 Arrays are fussy about type

In [19]:
py_list = [1, 1.5, 'A']
np.array(py_list)


array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

In [21]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

In [22]:
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [29]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)


In [24]:
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [25]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

In [32]:
np_array_1+10

array([11, 12, 13, 14, 15])

In [33]:
1+2.0

3.0

### 2.5 Multiplying by a Number

In [34]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)  


In [27]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [29]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)


In [31]:
py_list**2`b

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [32]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [37]:
py_list == 3

False

In [41]:
[3] == 3

False

In [34]:
py_list > 3

TypeError: '>' not supported between instances of 'list' and 'int'

In [35]:
np_array > 3

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [36]:
sum(py_list)


15

In [37]:
max(py_list)

5

In [38]:
min(py_list)

1

In [39]:
py_list.sum()`

AttributeError: 'list' object has no attribute 'sum'

In [41]:
np_array.sum()

15

In [43]:
np_array.mean()

3.0

In [44]:
np_array.max()

5

In [45]:
np_array.min()

1

## Exercise 1 :  Total recall?

### Similarities
1. Both are use to store data
*2. Both can be indexed*
### Differences
1. Lists can hold multiple data types while array can only hold same data type.
2. List cannot manage arithmetic operation while array can manage arithmetic operation.
### Dictionary
- It is used to store data values in key-value pairs


## Exercise 2 :  Index me

In [19]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

print(py_list[0],py_list[2],py_list[4],py_list[6],py_list[8])

a1 c3 e5 g7 i9


## Exercise 3 :  Capitalise Heros

In [29]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info["Tony Stark"] = superhero_info["Tony Stark"].upper()
superhero_info["Natasha Romanoff"] = superhero_info["Natasha Romanoff"].upper()
superhero_info["Stephen Strange"] = superhero_info["Stephen Strange"].upper()

print(superhero_info["Tony Stark"])
print(superhero_info ["Natasha Romanoff"])
print(superhero_info["Stephen Strange"])

IRON MAN
BLACK WIDOW
DOCTOR STRANGE


## Exercise 4 :  How many ones

In [30]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

In [44]:
import numpy as np
np_numbers = np.array(numbers)
x=np_numbers ==1
x.sum()

9